export const programmingQuotes: string[] = [
    "Programs must be written for people to read, and only incidentally for machines to execute. — Harold Abelson",
    "Simplicity is the soul of efficiency. — Austin Freeman",
    "Talk is cheap. Show me the code. — Linus Torvalds",
    "The best way to predict the future is to invent it. — Alan Kay",
    "Programming isn't about what you know; it's about what you can figure out. — Chris Pine",
    "Code is like humor. When you have to explain it, it’s bad. — Cory House",
    "Bad code can always be improved. Bad architecture is much harder to fix. — Kevlin Henney",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. — Martin Fowler",
    "First, solve the problem. Then, write the code. — John Johnson",
    "Make it work, make it right, make it fast. — Kent Beck",
    "If you can't deploy it, it doesn’t work. — John K. Saw",
    "Programs are meant to be read by humans and only incidentally for computers to execute. — Donald Knuth",
    "The most disastrous thing you can ever learn is your first programming language. — Alan Kay",
    "Before software can be reusable, it first has to be usable. — Ralph Johnson",
    "A language that doesn’t affect the way you think about programming is not worth knowing. — Alan Perlis",
    "One of my most productive days was throwing away 1000 lines of code. — Ken Thompson",
    "The function of good software is to make the complex appear to be simple. — Grady Booch",
    "Optimism is an occupational hazard of programming: feedback is the treatment. — Kent Beck",
    "Programming is the art of algorithm design and the craft of debugging errant code. — Ellen Ullman",
    "Simplicity is prerequisite for reliability. — Edsger W. Dijkstra",
    "There are only two kinds of languages: the ones people complain about and the ones nobody uses. — Bjarne Stroustrup",
    "Real programmers can write assembly code in any language. — Larry Wall",
    "The trouble with programmers is that you can never tell what a programmer is doing until it’s too late. — Seymour Cray",
    "If debugging is the process of removing software bugs, then programming must be the process of putting them in. — Edsger W. Dijkstra",
    "The best performance improvement is the transition from the nonworking state to the working state. — J. Osterhout",
    "It's not a bug; it’s an undocumented feature. — Anonymous",
    "Code never lies, comments sometimes do. — Ron Jeffries",
    "Testing leads to failure, and failure leads to understanding. — Burt Rutan",
    "The goal of software engineering is to control complexity, not to create it. — Pamela Zave",
    "If you think it's simple, then you have misunderstood the problem. — Bjarne Stroustrup",
    "There is always one more bug to fix. — Lubarsky’s Law",
    "Deleted code is debugged code. — Jeff Sickel",
    "A good programmer is someone who always looks both ways before crossing a one-way street. — Doug Linder",
    "The best code is no code at all. — Jeff Atwood",
    "Programming is like writing a book... except if you miss a single comma on page 126, the whole thing makes no sense. — Unknown",
    "The proper use of comments is to compensate for our failure to express ourselves in code. — Robert C. Martin",
    "Software and cathedrals are much the same – first we build them, then we pray. — Anonymous",
    "The more code you have, the more places there are for bugs to hide. — Anonymous",
    "When in doubt, use brute force. — Ken Thompson",
    "The best thing about a boolean is even if you are wrong, you are only off by a bit. — Anonymous",
    "Inside every large program, there is a small program trying to get out. — Tony Hoare",
    "Programming is not about typing, it's about thinking. — Rich Hickey",
    "The act of describing a program in unambiguous detail and the act of programming are one and the same. — Kevlin Henney",
    "Java is to JavaScript what car is to carpet. — Chris Heilmann",
    "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live. — John Woods",
    "The computer was born to solve problems that did not exist before. — Bill Gates",
    "If you optimize everything, you will always be unhappy. — Donald Knuth",
    "It’s not at all important to get it right the first time. It’s vitally important to get it right the last time. — Andrew Hunt",
    "Most software isn’t designed. It’s just grown by hacking. — Jack Reeves",
];
